language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install poetry twine
script:
  - poetry install
  - make build
deploy:
  provider: script
  script: make upload
  on:
    branch: master
    tags: true
env:
  - TWINE_USERNAME=ttymck
# matrix:
#   include:
#     - os: linux
#       dist: xenial
#     - os: osx
#       osx_image: xcode7.2